AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates secrets used in different IndirectDebit microservices."
# Parameters are defined in your template and allow you to input custom values when you create or update a stack
Parameters: 
  EnvironmentName:
    Type: String
    Default: test
    Description: "Your deployment environment: DEV, TEST, QA, PROD"
  CountryCode:
    Type: String
    Default: au
    Description: "Country code"
  ServiceName: 
    Default: shared
    Description: "Name of the service secret is being created for"
    Type: String
    
Resources:
  # Creates the empty secret for the given service. Key/Value pair will be added manually in that secret
  ServiceSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub ${CountryCode}_${EnvironmentName}_${ServiceName}
      Description: This secret contains the keys needed for Indirect Debit Microservice
  
  # Managed policy for the IAM roles for microservices to be able to talk to secret manager to fetch this secret        
  SecretManagedPolicy:
#    Type: 'AWS::SecretsManager::ResourcePolicy'
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Least privilege policy for the task of the batch job.
      ManagedPolicyName: !Sub ${CountryCode}_${EnvironmentName}_${ServiceName}-secret-read-ap
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref ServiceSecret
#            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CountryCode}_${EnvironmentName}_${ServiceName}'

              
Outputs: 
  SecretManagedPolicy:
    Value: !Ref SecretManagedPolicy
    Export:
      Name: !Sub ${CountryCode}:${EnvironmentName}:${ServiceName}-secret-read-ap
  